### ISSUE TITLE
[BUG] Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode' on Windows

### ISSUE THREAD

**Issue by DominatorDuck** [googlesamples/unity-jar-resolver#412]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.11f1
  * External Dependency Manager version: 1.2.161
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android, ResolverVersionHandler
  * Plugins SDK in use: None
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Given a vanilla 3D project in Unity 2020.1.11f1, upon pressing play I get the following error log:

```
Assembly 'Packages/com.google.external-dependency-manager/ExternalDependencyManager/Editor/Google.IOSResolver_v1.2.161.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Steps to reproduce:
- Open a Unity project (in Unity 2020.1.11f1) with the External Dependency Manager package.
- Press the play button.
- Notice the error log.

Notes:
- To create this project I originally made a project for Unity version 2019.4.8f1 and the upgraded it to 2020.1.11f1.
- The error does no occur with the very same project in Unity 2019.4.8f1.
- The only non-default package in the project is the External Dependency Manager.
- The Unity 2020.1.11f1 installation has only Windows (IL2CPP) and Android Build support.
- External Dependency Manager settings are as they come out of the package installation.
- Enabling Verbose Logging does not seem to give any more relevant information.
- Changing Build platform (from Windows to Android) seems to have no effect on the bug.

#### Please answer the following, if applicable:
What's the issue repro rate? 100%

What happened? How can we make the problem occur?

The Assembly 'Packages/com.google.external-dependency-manager/ExternalDependencyManager/Editor/Google.IOSResolver_v1.2.161.dll' fails to load.

You can reproduce the issue by following the repro steps with the proper Unity installation by using this sample project:
[https://drive.google.com/file/d/1llavcZxSVk7icuCpLv65QPrnjgV81u93/view?usp=sharing](url)

**Comment by arcv** [comment]
For quick fix, you can install "iOS Build Support" module from Unity Hub. That fixes the issue.

**Comment by DominatorDuck** [comment]
Thanks for the comment, @arcv, that certainly works as a temporary fix. 
@cynthiajoan, I noticed you marked the tread as in need of info, can you please let me know what info I can provide to help solve the issue.

**Comment by vimanyu** [comment]
Hi @DominatorDuck,
Thanks for raising this issue. Newer versions of Unity have stricter checks on inspecting dependent libraries. Does this error block the build altogether? 

I am flagging this as a bug for us to follow on.

**Comment by DominatorDuck** [comment]
Hi @vimanyu. 
Thanks for coming back on this.
The error does not block the build, it just appears every time you build or run the game - so it shows up often enough, but it's not of the breaking stuff variety. 
Other than the error being logged, nothing else seems to be broken or affected.

**Comment by vimanyu** [comment]
Good to know that it is not blocking or breaking anything. Yes, we will take a look at ways to avoid this error.

**Comment by wimachtendink** [comment]
Hello,

(apologies in advance if this is not helpful)

It seems like this issue is resolved by deselecting all of the "select platform for plugin" options on [maybe some combination of, but I chose] all firebase DLL assets in the ExternalDependencyManager folder and Firebase>Plugins>iOS folder

**Comment by TheAncientDragon** [comment]
Hi, i happened to have the same problem today.. made unity upgrade and after relaunching i got the same error, the only difference is the version of IOSResolver, your one is _v1.2.161.dll and mine is _v1.2.163..
Interesting to point is that i dont use IOS, in fact i didnt even import it.
Im using Android, like ever.
And im like, why the hell im having an IOS resolver problem if i never used, never installed nor activated it..

**Comment by VergilUa** [comment]
Make sure you've got Gradle Daemon enabled in Resolver Settings (Assets -> External Dependency Manager -> Android Resolver -> Settings) when using OpenJDK + JDK 14+ on the same system. 

This is probably caused by it being disabled.

**Comment by rameezfayyaz** [comment]
If you are not planning on using IOS platform resolver just change the "Scripting Backend" in "Project Settings -> Player -> Configuration" to "MONO" from "IL2CPP" and the error should go away. This worked for me.

**Comment by soundmartell** [comment]
Hello,  as @arcv said if you have not "iOS Build Support" installed you will have this error bothering you often enough. 
In my case I could not compile the Game, some errors appeared as well.  
If I disable the Validate Reference in Google.IOSResolver_v1.2.165 the error doesnt show but still not able to compile.
I did not try MONO as @rameezfayyaz because Google is not supporting 32 bits APP.  64 Bits only support  IL2CPP.
THE ONLY SOLUTION FOR NOW: Using the Unity Hub Add modules iOS Build support.

**Comment by TrongHieu90** [comment]
@vimanyu Has this been fixed yet ? Im using Unity 2020 LTS version and this issue still happens

**Comment by jvrieling** [comment]
I am using Unity 2020.3.16 and was getting this error. I'm not releasing on iOS, but installing the modules seems to have fixed the error. Thanks, @soundmartell !

**Comment by fararugames** [comment]
I updated the project from 2019 to 2020, the IOS module was connected for 2019, but not for 2020. After the update, this error appeared.

 This advice helped solve the issue. Thanks
> For quick fix, you can install "iOS Build Support" module from Unity Hub. That fixes the issue.

**Comment by astyd256** [comment]
Still have the same bug. It's quite sad that i have to use my low space on ssd for this sh#t.

**Comment by Zarkend** [comment]
Still happening, fix is to install iOS Build Support

**Comment by genin43** [comment]
Why can't you just fix this bug?

**Comment by binouze** [comment]
Hi,
No need to install iOS Build support, just uncheck the "Validate References" checkbox in the plugin inspector.

**Comment by sjnilan** [comment]
2021.3.4f1 also have the issue. I found it today.

**Comment by BenjaminSimsMK** [comment]
Happens in 2021.3.3f1. We have a lot of non programmers on our project who use Unity frequently. Having to get them to install Android -and- iOS support which they will never need, just to avoid this error, is really annoying. 

Installing modules we do not need is not a solution, especially considering we're not running the dependency manager outside of builds.

**Comment by PatrionDigital** [comment]
> Installing modules we do not need is not a solution, especially considering we're not running the dependency manager outside of builds.
I want to second this. I just installed the GameAnalytics SDK for a WebGL build. No intention of deploying on iOS or Android for this particular project, so this "fix" is just not good enough.

**Comment by ahmedaniss25** [comment]
problem fixed here: https://youtu.be/z4ERv0oLJXc

**Comment by somedeveloper00** [comment]
@ahmedaniss25 this workaround has already been mentioned by @arcv about 2 years ago on this very topic https://github.com/googlesamples/unity-jar-resolver/issues/412#issuecomment-724243829

**Comment by firesightstudios** [comment]
still an issue on 2022.3.0

**Comment by firesightstudios** [comment]
> Hi, No need to install iOS Build support, just uncheck the "Validate References" checkbox in the plugin inspector.

I see no option for this. Where is it exactly ?

**Comment by firesightstudios** [comment]
> Hi, No need to install iOS Build support, just uncheck the "Validate References" checkbox in the plugin inspector.

The problem with this is when you save in one project and push to source, you have to remember to enable it every time when pulling down on ios.

**Comment by CaseyHofland** [comment]
I'm going to uncheck "validate references".

However, for the Google team, this is very easy to fix on your end. All you need is to create a folder (call it IOS) in which you put the IOSResolver, as well as an assembly definition with only IOS checked.

![Platforms](https://github.com/googlesamples/unity-jar-resolver/assets/27729987/6f651a9f-b71c-479b-ac9d-62c829b1cfe8)

This will make sure to only compile the IOSResolver if you are working with IOS.

**Comment by nndwn** [comment]
![image](https://github.com/googlesamples/unity-jar-resolver/assets/25237268/415acebd-b08c-4d8c-a094-e5198d0a930a)
uncheck all general

**Comment by somedeveloper00** [comment]
> ![image](https://private-user-images.githubusercontent.com/25237268/294737013-415acebd-b08c-4d8c-a094-e5198d0a930a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjQwNjEsIm5iZiI6MTcwNDY2Mzc2MSwicGF0aCI6Ii8yNTIzNzI2OC8yOTQ3MzcwMTMtNDE1YWNlYmQtYjA4Yy00ZDhjLWEwOTQtZTUxOThkMGE5MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIxNDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmY1OGU5OGFmYTNkNjNlZGMzMzg3MmUyZDgyOTEzOTEwNDBiYzQ2YjJlYTk1NmNiMDM5OTUwZDJhNjNkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Uij3C4zVyuHcFVBhUvqW_vPWEbPUKnaj0MMXlXY_PA) uncheck all general
> 
> https://docs.unity3d.com/Manual/PluginInspector.html

I wouldn't modify the sdk files directly, because then it'd become a task which you and next developers will have to do for every update. A task like that is easy to miss. Howevrr if installing iOS module is impossible for some machines, then yeah 

+ On another note, it's crazy how an issue so simple to fix such as this is still not fixed by the package maintainers...

**Comment by Zamaroht** [comment]
Hello!

In case it's useful for anyone browsing and landing in this page, I was having a crash on Android at startup with Firebase and Crashlytics installed. Logcat was telling me that "Crashlytics build ID is missing", and I noticed that the "FirebaseCrashlytics.androidlib" folder that's generated automatically at build time in my desktop machine was not getting generated in CI.

The build log had the following errors:
```
Assembly 'Packages/com.splabs.base.google-package-manager/ExternalDependencyManager/Editor/1.2.179/Google.IOSResolver.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Assembly 'Packages/com.splabs.base.firebase/Firebase/Editor/Firebase.Crashlytics.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Symbol file LoadedFromMemory is not a mono symbol file
Assembly 'Packages/com.splabs.base.firebase/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Turns out that the Firebase.Editor.dll and Firebase.Crashlytics.Editor.dll files are in charge of auto-generating the FirebaseCrashlytics.androidlib folder at build time.

Also, I'm using the UnityCI docker images, and the android docker images in particular do not have iOS Build Support installed.

As suggested in this issue, unselecting the "Validate References" checkboxes from both Firebase.Editor.dll and Firebase.Crashlytics.Editor.dll files solved the issue in CI for me, now everything is generated correctly.

**Comment by TigerHix** [comment]
Still having this issue in 2024. Can't believe such a trivial issue can take more than 4 years to fix. @CaseyHofland has already provided a solution, and the maintainers literally just needed to create an .asmdef file that take maybe 2 minutes.

**Comment by PTSY-17031999** [comment]
> ![image](https://private-user-images.githubusercontent.com/25237268/294737013-415acebd-b08c-4d8c-a094-e5198d0a930a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzUzMTksIm5iZiI6MTcxMjc3NTAxOSwicGF0aCI6Ii8yNTIzNzI2OC8yOTQ3MzcwMTMtNDE1YWNlYmQtYjA4Yy00ZDhjLWEwOTQtZTUxOThkMGE5MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4NTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMTUyODZjY2VlZWZkMmYzYzhlZTE1N2ZiZWNiOGUyNGE2NmQwOTAxMWZkMGE1ZWY5NTc5YTk3N2U5ZmVhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFZ19ktrdjN_LXTuK08y7rOMrNJtPctFffG5B_dv-mY) uncheck all general
> 
> https://docs.unity3d.com/Manual/PluginInspector.html

Thank you, this method works for me but the app cannot run

**Comment by chriscode2001** [comment]
Yes, load of rubbish. Install IOS stuff, for NO reason. Fix it!

**Comment by chriscode2001** [comment]
I turned off validate, but come on, really

**Comment by somedeveloper00** [comment]
how is this issue still not fixed??? it's been 4 years, and all it takes is to wrap the iOS stuff in a `#if`

**Comment by demiursos** [comment]
Since I only build Android, I deleted all iOS-related files and the problem was resolved. It's so easy.

**Comment by rico345100** [comment]
Why do I have to install iOS build support even though I'm not gonna build for iOS? This is totally non-sense.

**Comment by StephenHodgson** [comment]
One day this bug will be squashed 🙏

**Comment by Awais6** [comment]
it's been 4 years and it is not resolved yet, are they sleeping 😴😴😴

**Comment by StephenHodgson** [comment]
Got tired of it, so I fixed it (I think bc project is setup super complicated for what feels like no reason)

Opened #714

**Comment by CWilson-RhinoRock** [comment]
Please oh please can we get this fixed! Please someone go review @StephenHodgson 's [pull request^](https://github.com/googlesamples/unity-jar-resolver/pull/714) with the fix in there!

**Comment by argzdev** [comment]
Hi @CWilson-RhinoRock, I did see our engineer [commenting](https://github.com/googlesamples/unity-jar-resolver/pull/714#issuecomment-2683332150) on the PR. It should us sometime to check and make sure everything is working correctly. Rest assured this is under our radar.

**Comment by StephenHodgson** [comment]
Still a problem in 1.2.186

Tried with Unity 6000.0.49f1 with only Android and Windows IL2CPP modules installed. 

```
Assembly 'Packages/com.google.firebase.app/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```
