### ISSUE TITLE
Gradle Prebuild fails

### ISSUE THREAD

**Issue by smokiespartakus** [googlesamples/unity-jar-resolver#56]
I get "Resolution failed." when trying to Resolve Jars after enabling "Prebuild with Gradle". Any ideas how I can resolve this? I'm way over 64k references, so I need to strip the unused and was hoping prebuilding with gradle could do that.

Heres the error from Console

```
Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (-1):
Traceback (most recent call last):
  File "<string>", line 468, in <module>
  File "<string>", line 459, in main
  File "<string>", line 446, in process_args
  File "json\__init__.py", line 338, in loads
  File "json\decoder.py", line 366, in decode
  File "json\decoder.py", line 382, in raw_decode
ValueError: Invalid \escape: line 24 column 12 (char 863)
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStorey0:<>m__0(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

**Comment by johnb003** [comment]
I'll look into this.
To get started, I could use some more info:
* Which platform are you running on?
* Did you try the suggestions in the error:
    * BundleID (which you can correct in the Android Player Settings)
    * Valid android SDK path in the Unity preferences.
* Which version of Unity are you using?
* What sort of dependencies do you have Firebase + others?


You aren't quite to this part yet, but:
One of the unfinished parts of this feature is that if you switch to it, after using the traditional resolver, you'll need to remove the transitive dependencies the traditional resolver adds.

You can try removing just the set that gets added in this folder that's not related to some other plugin, for example if you simply add firebase analytics here are all of the libraries that get added:

![screen shot 2017-05-23 at 10 45 35 am](https://cloud.githubusercontent.com/assets/6802349/26368060/59fce802-3fa5-11e7-858f-a0d065875bf0.png)

When using the gradle resolver method, all of these dependencies will get packaged into a single proguard stripped library that is added to the plugins folder, so having these other libraries is redundant and will cause problems.

**Comment by johnb003** [comment]
by platform I mean development, (ie. windows or mac/linux) not the target platform.

**Comment by smokiespartakus** [comment]
Thanks for your reply.

Running on Windows 10

BundleID is the one I'm using to upload to google play, so I asume that's good enough. Android building normally works, so the SDK should be fine. I don't know if this requires a specific version? The highest one of build-tools I have installed is 25.0.2.

Unity Version 5.5.1f1

By dependecies, do you mean other libraries? I'm using a lot of plugins. Facebook, Helpshift, UnityPurchasing, Google-play-games to name a few.

Do I have to delete those folders? Perhaps only after using the gradle resolver?

**Comment by johnb003** [comment]
Thanks.

Hopefully you won't need to delete any other plugins. Only if those plugins included some extra dependency that's a really common one, would you have a problem.

Can you please attach your config.json.
This is a file that's written when attempting the resolve jars with the gradle resolver.
It's in your project root/Temp folder (sibling of /Assets)

If you don't see it, try running the resolve again.

Thanks.

**Comment by smokiespartakus** [comment]
Here you go. I've removed the app_id. The rest is generic.
```json
{
"config": {
    "app_id": "--",
    "sdk_version": "25",
    "min_sdk_version": "15",
    "build_tools_version": "25.0.2",
    "android_sdk_dir": "D:/AndroidSDK/sdk"
},
"project_deps": [
    ["com.google.android.gms", "play-services-base", "10.2.4"],
    ["com.google.firebase", "firebase-common", "10.2.4"],
    ["com.google.firebase", "firebase-app-unity", "3.0.3"],
    ["com.google.firebase", "firebase-messaging", "10.2.4"],
    ["com.google.firebase", "firebase-messaging-unity", "3.0.3"],
    ["com.google.android.gms", "play-services-games", "9.+"],
    ["com.google.android.gms", "play-services-nearby", "9.+"],
    ["com.google.android.gms", "play-services-auth", "9.+"],
    ["com.android.support", "support-v4", "23.1+"]
],
"extra_m2repositories": [
    "Assets/Firebase/m2repository"
],
"extra_proguard_configs": [
    "Assets\PlayServicesResolver\proguard-unity.txt",
    "Assets\PlayServicesResolver\proguard-messaging-workaround.txt"
]
}
```

**Comment by johnb003** [comment]
OK! now we're getting somewhere. The bug appears to be that on windows we encode the paths in the extra_proguard_configs, with backslashes, which get interpreted as escape sequences.

I'll look into this in the morning (pacific time).

**Comment by smokiespartakus** [comment]
Great! Thanks!

**Comment by johnb003** [comment]
I've uploaded a fix. Let me know if you have any other issues.
Also, compare the picture I posted, with the config you posted. Remove any libraries that were previously added to your project like the ones I have highlighted that match the libraries in the project_deps section of the config.

Effectively everything in the project_deps section will be inserted as a single proguard stripped combined package (if the gradle prebuild completes successfully).

**Comment by smokiespartakus** [comment]
Still fails.

I updated with the unitypackage, removed the old dll's and ran resolve.

It seems to be missing a 'gradle-template.zip' file.
```
Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (-1):
Traceback (most recent call last):
  File "<string>", line 468, in <module>
  File "<string>", line 460, in main
  File "<string>", line 184, in generate_gradle_build
  File "zipfile.py", line 756, in __init__
IOError: [Errno 2] No such file or directory: 'gradle-template.zip'
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStorey5:<>m__6(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```
My config.json now looks like this (seems there are still forward slash in som paths, dunno if that has anything to do with it)
```json
{
"config": {
    "app_id": "--",
    "sdk_version": "25",
    "min_sdk_version": "15",
    "build_tools_version": "25.0.2",
    "android_sdk_dir": "D:/AndroidSDK/sdk"
},
"project_deps": [
    ["com.google.android.gms", "play-services-base", "10.2.4"],
    ["com.google.firebase", "firebase-common", "10.2.4"],
    ["com.google.firebase", "firebase-app-unity", "3.0.3"],
    ["com.google.firebase", "firebase-messaging", "10.2.4"],
    ["com.google.firebase", "firebase-messaging-unity", "3.0.3"],
    ["com.google.android.gms", "play-services-games", "9.+"],
    ["com.google.android.gms", "play-services-nearby", "9.+"],
    ["com.google.android.gms", "play-services-auth", "9.+"],
    ["com.android.support", "support-v4", "23.1+"]
],
"extra_m2repositories": [
    "Assets/Firebase/m2repository"
],
"extra_proguard_configs": [
    "Assets\\PlayServicesResolver\\proguard-unity.txt",
    "Assets\\PlayServicesResolver\\proguard-messaging-workaround.txt"
]
}
```

**Comment by johnb003** [comment]
Are you sure you imported everything from the updated plugin, I just doubled checked on my end and the zip is present.

I'm trying to repro on a windows machine now to see if there's any other windows specific gotchas.

**Comment by smokiespartakus** [comment]
The file is there, but it apparently can't find it.

**Comment by smokiespartakus** [comment]
Hi, any ideas what I can do to get it to work? Possibly move the zip somewhere?

**Comment by johnb003** [comment]
Hi Smokie, I'm trying to reproduce the environment so I can make sure this works end-to-end. In the meantime if you want to dive in there are some ways you can help.

The fact that you've already been able to produce a config, and have all the files is good. The remaining work is all done with a tool on the command line that the jar resolver is trying to kick off. So you can try to run this tool manually and see if you can help identify the issue.

On windows we compile the python script since python doesn't come standard on the system, but if you'd like to install python you can run the python script directly instead of the exe.

After the failed jar resolver attempt, you'll want to execute this in the root folder of your project.

You can run the script without modification by running Assets\PlayServicesResolver\generate_gradle_prebuild.exe -c "Temp\config.json" -b "Temp\GenGradle" -o "Assets\Plugins\MergedOutput"

or if you get python working, you should be able to easily edit the script and test with something like:
python Assets\PlayServicesResolver\generate_gradle_prebuild.py -c "Temp\config.json" -b "Temp\GenGradle" -o "Assets\Plugins\MergedOutput"

You may have to tweak these paths slightly if I didn't get it exactly right.

The options are
-c is your config file
-b is where to generate the intermediate files
-o is where to output the results.

Feel free to open up the script and make some tweaks.
It looks for "gradle-template.zip" and "volatile_paths.json" in the same folder as the python script, perhaps the logic there is failing there on windows?

**Comment by smokiespartakus** [comment]
Great - thanks!

I'll give that a go in the morning (CET), when I get to my work computer, and let you know how it goes.

Thanks again
/jonas

**Comment by smokiespartakus** [comment]
Hi,
Running the python script directly gets past the zip problem. (after I changed a comma to a "as" because of python version i think)

But then it fails on line 252 because p.returncode == 1  (I debugged it; dunno what 1 means)

I've attached the output given with -d option.
* Well, uhm - apparently windows cannot output stuff properly to a file, so all I can get is the notes, all the warnings are ommitted from the file and printet in console anyway... stupid. 
[out_debug.txt](https://github.com/googlesamples/unity-jar-resolver/files/1057371/out_debug.txt)
So I've attached some of the warnings in a separate file.
[out_warnings.txt](https://github.com/googlesamples/unity-jar-resolver/files/1057379/out_warnings.txt)

Gonna keep fiddling with it to see if I can get something else out of it, but it seems to fail because of a bunch of warnings.

Regarding the zip, I agree that it's probably something about paths in windows that is bugging. But since it's working in the python script, my effort right now is gonna go towards making the next steps work.

**Comment by smokiespartakus** [comment]
So, I've just tried to run the python script in a new project with only firebase messaging and the updated version of the jar-resolver from here, and it builds. So I must have som proguard settings somewhere that aren't working. 

I'll have to investigate further.

Any idea if I can somehow get either gradle or the python script to point me in a direction?

**Comment by smokiespartakus** [comment]
More info: I reverted my project to before installing firebase, and then tried reinstalling it. After doing this the python script actually succeeded.

But testing the app, it broke down while trying to access the firebase functionality, so resolving the jars didnt include them in the build apparently.

After that I unticked the "gradle option" in resolver settings, and tried resolving again. This installed a lot of things, and made my unity build fail because of too many references in dex.

So I ticked "gradle option" again. And now it's failing like it did before (2 posts ago with the output files).

So back to square one (more or less).

**Comment by johnb003** [comment]
The Gradle build doesn't clean up after itself when switching to regular
resolver builds (part of why it's still experimental -- and these bugs). So
you'll have to delete that combined output if using the regular build again.

If switching from the regular build to gradle, you might also have the
issue of all those things it adds in Assets/Plugins which I was describing
at the beginning of this thread, you'll have to get rid of those if using
gradle build again.

" it broke down while trying to access the firebase functionality". Any
errors in logcat or additional information on this?

Do the testapps work for you when using gradle build?

`John

**Comment by smokiespartakus** [comment]
Thanks - I'll clean up and try again tomorrow.

Logcat said that firebase did not exist and asked if the depencies was included in the app. Or something like that. Didn't save the error. I'll start over with that tomorrow too, and see what I can get out of it. 

Does the unity script do something after exe/py has been run that I might be missing by running it manually?  I tried building an exe with a working py-file, but couldnt get that to work on windows. Might give that another go as well.

I haven't used any testapps. Is it these you're talking about? https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp

/Jonas

**Comment by smokiespartakus** [comment]
Regarding the gradle-template.zip, I managed to make an exe and it seems that as an exe file it doens't register __file__ as a path, so it's empty.
If I change to
```python
TEMPLATE_ZIP = "Assets\\PlayServicesResolver\\gradle-template.zip"
INTERMEDIATE_PATHS_CONFIG = "Assets\\PlayServicesResolver\\volatile_paths.json"
```
It seems to work.
Hope it helps.

**Comment by smokiespartakus** [comment]
I found a solution to the warnings I got. Apparently gradle/proguard did not like the versions of the libraries in the config.json. So I got it to complete the build by changing them to the latest.

Edited Temp/config.json 
from
```
"project_deps": [
    ["com.google.android.gms", "play-services-base", "10.2.4"],
    ["com.google.firebase", "firebase-common", "10.2.4"],
    ["com.google.firebase", "firebase-app-unity", "3.0.3"],
    ["com.google.firebase", "firebase-messaging", "10.2.4"],
    ["com.google.firebase", "firebase-messaging-unity", "3.0.3"],
    ["com.google.android.gms", "play-services-games", "9.+"],
    ["com.google.android.gms", "play-services-nearby", "9.+"],
    ["com.google.android.gms", "play-services-auth", "9.+"],
    ["com.android.support", "support-v4", "23.1+"]
],
```
to
```
"project_deps": [
    ["com.google.android.gms", "play-services-base", "10.2.6"],
    ["com.google.firebase", "firebase-common", "10.2.6"],
    ["com.google.firebase", "firebase-app-unity", "3.0.3"],
    ["com.google.firebase", "firebase-messaging", "10.2.6"],
    ["com.google.firebase", "firebase-messaging-unity", "3.0.3"],
    ["com.google.android.gms", "play-services-games", "10.+"],
    ["com.google.android.gms", "play-services-nearby", "10.+"],
    ["com.google.android.gms", "play-services-auth", "10.+"],
    ["com.android.support", "support-v4", "23.1+"]
],
```
After that, unity complained that the newly added so-libraries were using the same architecture, so I had to manually change from `arm` to `x86` on the two in the `x86` folder.

After cleaning up some duplicate jar/aar libraries I got it to build. 

Triggering the Firebase messaging plugin from unity produced this error in logcat:
```
06-08 13:00:14.975: E/Unity(18849): [API]data succes run errorFirebase.InitializationException: Firebase's libApp.so was not found for this device's architecture
06-08 13:00:14.975: E/Unity(18849): in your APK.
06-08 13:00:14.975: E/Unity(18849): On Android, Firebase requires C/C++ and Java components
06-08 13:00:14.975: E/Unity(18849): that are distributed with the Firebase and Android SDKs.
06-08 13:00:14.975: E/Unity(18849): It's likely the required dependencies for Firebase were not included
06-08 13:00:14.975: E/Unity(18849): in your Unity project.
06-08 13:00:14.975: E/Unity(18849): Assets/Plugins/Android/ in your Unity project should contain
06-08 13:00:14.975: E/Unity(18849): AAR files in the form firebase-*.aar
06-08 13:00:14.975: E/Unity(18849): You may have disabled the Android Resolver which would
06-08 13:00:14.975: E/Unity(18849): have added the AAR dependencies for you.
06-08 13:00:14.975: E/Unity(18849): Do the following to enable the Android Resolver in Unity:
06-08 13:00:14.975: E/Unity(18849): * Select the menu option 'Assets -> Play Services Resolver -> 
06-08 13:00:14.975: E/Unity(18849):   Android Resolver -> Settings'
06-08 13:00:14.975: E/Unity(18849): * In the Android Resolver settings check
06-08 13:00:14.975: E/Unity(18849):   'Enable Background Resolution'
06-08 13:00:14.975: E/Unity(18849): * Select the menu option 'Assets -> Play Services Resolver ->
06-08 13:00:14.975: E/Unity(18849):   Android Resolver -> Resolve Client Jars' to force Android
06-08 13:00:14.975: E/Unity(18849):   dependency resolution.
06-08 13:00:14.975: E/Unity(18849): * Rebuild your APK and deploy.
06-08 13:00:14.975: E/Unity(18849):   at Firebase.FirebaseApp.TranslateDllNotFoundException (System.Action closur
```
So as far as I can see, it checks the so-files for all the libraries and if they're duplicate it complains, but it's not including or using them in the build afterwards... or something...

**Comment by smokiespartakus** [comment]
Hi,
Any idea how I can resolve this issue with the wrong architecture for libApp.so file?
/jonas

**Comment by stewartmiles** [comment]
Hi Jonas, John is now unfortunately out on vacation for a couple of weeks.

It sounds like you've run into a similar issue that we solved in the AAR
integration for non-Gradle builds.

Essentially we had to write a load of code (see
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/DefaultResolver.cs#L375)
to
unpack each AAR strip the architectures we're not using from it and then
repackage the AAR.

When you mention you "had to manually change from arm to x86 on the two in
the x86 folder." I hope you didn't just rename the directories.  You'll
either have to remove the x86 or arm directory depending upon whether
you're targeting arm or x86 respectively.

Cheers,
Stewart

**Comment by smokiespartakus** [comment]
Hi Stewart
Thanks for the update!

By "manually change from arm to x86" I meant that I, in Unity editor, selected x86 architecture instead of arm, which was selected for both libApp.so files (one in each folder) and the same for the other .so files. I assume that Unity (or Android?) would then include the correct files.

Since the only produces one file (I think(?) - don't have the repo here), I guess it might be possible to do this manually. I shall try and have a look at that tomorrow.

Cheers
/jonas

**Comment by stewartmiles** [comment]
I think the problem with just configuring metadata in Unity (e.g selecting
x86 vs. arm for the shared libraries) is that Android's Gradle build plugin
has no idea about this and will blindly pull in all architecture shared
libraries referenced by the Gradle project.  If you delete the architecture
you don't need from your project then you can be sure it's only including
the shared library for the target architecture.  You can validate the
shared libraries are included in the APK by simply unzipping the APK and
taking a look inside (APKs are just zip files).

Cheers,
Stewart

**Comment by smokiespartakus** [comment]
Aha - that makes sense. I'll try that too.

Cheers

**Comment by smokiespartakus** [comment]
Hi,
I think I got it working - I moved the `MergedOutput` folder from `Assets/Plugins` to Assets/Plugins/Android` and now it seems to work. I got my Registration Token from firebase messaging at least.

I'm not sure everything is properly fixed in this repo yet though, because it was with an updated py-file that I built into exe, and then I fixed the problems with the config.json I mentioned earlier too.

But anyway - thanks for all your help. At least now I have a way of building.

Cheers
/Jonas

**Comment by johnb003** [comment]
Jonas,

This has been open for a long time and there were quite a few issues you ran into to get this to work. I really want to thank you for your patience and willingness to dig through this with us.

With the latest version, all of the major problems you've run into should be addressed:
[85b48c4](https://github.com/googlesamples/unity-jar-resolver/commit/85b48c435577d866735d5d9c1d7553819573af66)

Re-iterating all of the issues you ran into here:
* Redundancy of firebase dependencies when switching between regular and gradle prebuild resolver methods. -- We now cleanup when switching.
    * That also was likely why you had success recreating your project to get things to work.
* Windows path had unescaped backslashes -- fixed earlier.
* You were targeting a specific ABI version and the others weren't being removed -- Fixed!
* Unable to locate the gradle-template.zip and other data files on windows -- Fixed.

Non-issues:
* Bad proguard configs cause a failed build -- Sounds like a bad release, which was fixed in a later version.
* MergedOutput is always put in Assets/Plugins/Android, the reason it wasn't was because I gave you the wrong command line option earlier for running the script by hand when debugging.

**Comment by smokiespartakus** [comment]
FYI
Still getting this error
```
Error (-1):
Traceback (most recent call last):
  File "<string>", line 468, in <module>
  File "<string>", line 460, in main
  File "<string>", line 184, in generate_gradle_build
  File "zipfile.py", line 756, in __init__
IOError: [Errno 2] No such file or directory: 'gradle-template.zip'
generate_gradle_prebuild returned -1
```
I can fix it by running the pythong myself, but just for other users

**Comment by smokiespartakus** [comment]
Just realized that you removed the python files from the package, so actually I can't...

**Comment by johnb003** [comment]
They are extracted as resources from the dll. If you have the old files
still present somehow (the version handler is supposed to clean them out),
then it might be using the old script.

**Comment by smokiespartakus** [comment]
Well, they aren't present, and that's the problem since the script is still failing when running via unity

**Comment by johnb003** [comment]
are you using the last plugin released with firebase, or the most recent
one from github?

**Comment by johnb003** [comment]
The fix for this specific issue was in 1.2.46.0 which was released only on Github and just missed the most recent Firebase build (4.1.0). You will need to download the unity package from Github and install it separately from the Firebase Unity plugins.

**Comment by smokiespartakus** [comment]
Like I wrote above, I already tried that version, it still fails. I can give it another go in a moment and let you know how it goes.

**Comment by johnb003** [comment]
Sorry I missed your note about which version you tested before.

The script, and the gradle-template.zip and all the other little data files should all get extracted to:
Temp/PlayServicesResolverGradlePrebuild

That's where the python script lives, and as you've said before that's where __FILE__ would be used to detect the script path which wouldn't work on windows.

The reason is that on Windows, the exe actually extracts the script and all the necessary environment into a temporary folder somewhere as a little bundle, and then executes that, so __FILE__ would be wrong, in that case though there's another way to get where the bundle was extracted from, and I am using that.

So, I wonder what *IS* happening in your case? Feel free to test the rest of the pipeline by using verbose to get the command line that is run, and edit it for executing python directly. There's a note here about getting the verbose logging so you can see how the plugin executes the script:
https://github.com/googlesamples/unity-jar-resolver/blob/master/gradle_prebuild.md#debugging

**Comment by smokiespartakus** [comment]
Cheers - I'll give it a go on monday... Got it working the other day (running the python script from vx.x.39) but trying to include facebook sdk broke everything,,, I'll try to keep you up to date...
